function operations_ = decodeNodes_(~, active, functionSet, genes, functions, connections)
    operations_ = '';

    for i = 1:length(active)
        if active(i) <= 4
            operations_ = [ ...
                operations_, ...
                sprintf('\n'), ...
                'Node ', ...
                num2str(active(i)), ...
                ' = input (', ...
                num2str(active(i)), ...
                ')' ...
            ];
        else
            operations_ = [ ...
                operations_, ...
                sprintf('\n'), ...
                'Node', ...
                num2str(active(i)), ...
                '=', ...
                functionSet(genes(functions(active(i)))), ...
                '(', ...
                num2str(genes(connections{1}(active(i)))), ...
                ',', ...
                num2str(genes(connections{2}(active(i)))), ...
                ')' ...
            ];
        end
    end
end
